### ISSUE TITLE
SkinEditSectionLinks: Glyphicon HTML wrongly escaped

### ISSUE THREAD

**Issue by respiranto** [thaider/Tweeki#154]
Hi,

we noticed that the pencil-shaped edit button next to section headings is no longer rendered, instead, the HTML contains an escaped version of the required span tag.

We run MediaWiki 1.34 with Tweeki master/HEAD.

The issue can be circumvented by replacing in includes/Hooks.php the line
    $text = $icon . ( ( $icon != '' ) ? ' ' : '' ) . $text;
with
    $text = new HTMLArmor( $icon . ( ( $icon != '' ) ? ' ' : '' ) . $text );

This may be related to #69.

Greetings,
Einhard Leichtfuß

**Comment by thaider** [comment]
Thanks for reporting! However, the proposed solutions seems not to work with older version of MediaWiki. I tested in 1.31.0 and got the following error:

```Object of class HtmlArmor could not be converted to string in /var/www/semorg/w/includes/Html.php on line 215```

As 1.31 is a LTS release I wouldn't drop support for the moment being...

**Comment by Serveurperso** [comment]
I get a similar problem with the MediaWiki version 1.34.1 and Tweeki 1.1.1 (e3366cb) 17 mai 2020 à 22:47

The text "<span class="glyphicon glyphicon-pencil"></span>" appear when mouse hover.

**Comment by paikwiki** [comment]
I fixed same issue by @respiranto 's [comment](https://github.com/thaider/Tweeki/issues/154#issue-566462053) above.

> I get a similar problem with the MediaWiki version 1.34.1 and Tweeki 1.1.1 ([e3366cb](https://github.com/thaider/Tweeki/commit/e3366cb2d4a0e23dec3a5e600fb291a948aa0a86)) 17 mai 2020 à 22:47
> The text `<span class="glyphicon glyphicon-pencil"></span>` appear when mouse hover. The circumventing don't apply on my version:(

**Comment by Jyosua** [comment]
This is still an issue now with Mediawiki 1.35 and Tweeki 1.1.2

**Comment by thaider** [comment]
Thanks for reporting, should be fixed now.
